<?php

require_once dirname(__FILE__).'/../src/Tinypass.php';

/**
 * Test class for TinyPass.
 * Generated by PHPUnit on 2011-03-02 at 02:32:11.
 */
class TinyPassTest extends PHPUnit_Framework_TestCase {

	public function testEndPoints() {
		TinyPass::$SANDBOX = false;
		TinyPass::$API_ENDPOINT_DEV = null;
		$this->assertEquals("https://api.piano.io", TinyPass::config()->getEndPoint());

		TinyPass::$SANDBOX = true;
		$this->assertEquals("https://sandbox.piano.io", TinyPass::config()->getEndPoint());

		TinyPass::$API_ENDPOINT_DEV = "";
		$this->assertEquals("https://sandbox.piano.io", TinyPass::config()->getEndPoint());

		TinyPass::$API_ENDPOINT_DEV = "http://test.com";
		$this->assertEquals("http://test.com", TinyPass::config()->getEndPoint());


		$config = TinyPass::config("aid", "pk", true);
		print_r($config);
		$this->assertEquals("aid", $config->AID);
		$this->assertEquals("pk", $config->PRIVATE_KEY);
		$this->assertEquals(true, $config->SANDBOX);
	}

}
?>
